services:
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_USER: "dezzzmond"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "dev"
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
