# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: auth.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'auth.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nauth.proto\x12\x04\x61uth\"\"\n\x11GetPayloadRequest\x12\r\n\x05token\x18\x01 \x01(\t\"r\n\x12GetPayloadResponse\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0c\n\x04role\x18\x02 \x01(\t\x12\x12\n\nexpires_at\x18\x03 \x01(\t\x12\x14\n\x0cservice_name\x18\x04 \x01(\t\x12\x13\n\x0bpermissions\x18\x05 \x03(\t\"\x1f\n\x0eGetUserRequest\x12\r\n\x05token\x18\x01 \x01(\t\"\x98\x03\n\x0fGetUserResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x13\n\x0b\x65xternal_id\x18\x02 \x01(\t\x12\x0c\n\x04role\x18\x03 \x01(\t\x12\x15\n\rexternal_role\x18\x04 \x01(\t\x12\x0c\n\x04name\x18\x05 \x01(\t\x12\x0f\n\x07surname\x18\x06 \x01(\t\x12\x12\n\npatronymic\x18\x07 \x01(\t\x12\r\n\x05\x65mail\x18\x08 \x01(\t\x12\x0f\n\x07\x66\x61\x63ulty\x18\t \x01(\t\x12\r\n\x05login\x18\n \x01(\t\x12\x12\n\nlast_login\x18\x0b \x01(\t\x12\x12\n\ncreated_at\x18\x0c \x01(\t\x12\x0b\n\x03sex\x18\r \x01(\t\x12\x14\n\x0cstudy_status\x18\x0e \x01(\t\x12\x14\n\x0c\x64\x65gree_level\x18\x0f \x01(\t\x12\x13\n\x0bstudy_group\x18\x10 \x01(\t\x12\x16\n\x0especialization\x18\x11 \x01(\t\x12\x0f\n\x07\x66inance\x18\x12 \x01(\t\x12\x0c\n\x04\x66orm\x18\x13 \x01(\t\x12\x12\n\nenter_year\x18\x14 \x01(\t\x12\x0e\n\x06\x63ourse\x18\x15 \x01(\t\x12\x0c\n\x04type\x18\x16 \x01(\t2\x86\x01\n\x0b\x41uthService\x12?\n\nGetPayload\x12\x17.auth.GetPayloadRequest\x1a\x18.auth.GetPayloadResponse\x12\x36\n\x07GetUser\x12\x14.auth.GetUserRequest\x1a\x15.auth.GetUserResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETPAYLOADREQUEST']._serialized_start=20
  _globals['_GETPAYLOADREQUEST']._serialized_end=54
  _globals['_GETPAYLOADRESPONSE']._serialized_start=56
  _globals['_GETPAYLOADRESPONSE']._serialized_end=170
  _globals['_GETUSERREQUEST']._serialized_start=172
  _globals['_GETUSERREQUEST']._serialized_end=203
  _globals['_GETUSERRESPONSE']._serialized_start=206
  _globals['_GETUSERRESPONSE']._serialized_end=614
  _globals['_AUTHSERVICE']._serialized_start=617
  _globals['_AUTHSERVICE']._serialized_end=751
# @@protoc_insertion_point(module_scope)
