# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: permissions.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'permissions.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11permissions.proto\x12\x0bpermissions\"7\n\x10\x43reatePermission\x12\r\n\x05title\x18\x02 \x01(\t\x12\x14\n\x0cverbose_name\x18\x03 \x01(\t\"=\n\nPermission\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x03 \x01(\t\x12\x14\n\x0cverbose_name\x18\x04 \x01(\t\"6\n\x1eGetPermissionsByServiceRequest\x12\x14\n\x0cservice_name\x18\x01 \x01(\t\"O\n\x1fGetPermissionsByServiceResponse\x12,\n\x0bpermissions\x18\x01 \x03(\x0b\x32\x17.permissions.Permission\"i\n\x1e\x43reateServicePermissionRequest\x12\x14\n\x0cservice_name\x18\x01 \x01(\t\x12\x31\n\npermission\x18\x02 \x01(\x0b\x32\x1d.permissions.CreatePermission\"N\n\x1f\x43reateServicePermissionResponse\x12+\n\npermission\x18\x01 \x01(\x0b\x32\x17.permissions.Permission\"c\n\x1eUpdateServicePermissionRequest\x12\x14\n\x0cservice_name\x18\x01 \x01(\t\x12+\n\npermission\x18\x02 \x01(\x0b\x32\x17.permissions.Permission\"!\n\x1fUpdateServicePermissionResponse\",\n\x1e\x44\x65leteServicePermissionRequest\x12\n\n\x02id\x18\x01 \x01(\t\"!\n\x1f\x44\x65leteServicePermissionResponse2\xeb\x03\n\x11PermissionService\x12t\n\x17GetPermissionsByService\x12+.permissions.GetPermissionsByServiceRequest\x1a,.permissions.GetPermissionsByServiceResponse\x12t\n\x17\x43reateServicePermission\x12+.permissions.CreateServicePermissionRequest\x1a,.permissions.CreateServicePermissionResponse\x12t\n\x17UpdateServicePermission\x12+.permissions.UpdateServicePermissionRequest\x1a,.permissions.UpdateServicePermissionResponse\x12t\n\x17\x44\x65leteServicePermission\x12+.permissions.DeleteServicePermissionRequest\x1a,.permissions.DeleteServicePermissionResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'permissions_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CREATEPERMISSION']._serialized_start=34
  _globals['_CREATEPERMISSION']._serialized_end=89
  _globals['_PERMISSION']._serialized_start=91
  _globals['_PERMISSION']._serialized_end=152
  _globals['_GETPERMISSIONSBYSERVICEREQUEST']._serialized_start=154
  _globals['_GETPERMISSIONSBYSERVICEREQUEST']._serialized_end=208
  _globals['_GETPERMISSIONSBYSERVICERESPONSE']._serialized_start=210
  _globals['_GETPERMISSIONSBYSERVICERESPONSE']._serialized_end=289
  _globals['_CREATESERVICEPERMISSIONREQUEST']._serialized_start=291
  _globals['_CREATESERVICEPERMISSIONREQUEST']._serialized_end=396
  _globals['_CREATESERVICEPERMISSIONRESPONSE']._serialized_start=398
  _globals['_CREATESERVICEPERMISSIONRESPONSE']._serialized_end=476
  _globals['_UPDATESERVICEPERMISSIONREQUEST']._serialized_start=478
  _globals['_UPDATESERVICEPERMISSIONREQUEST']._serialized_end=577
  _globals['_UPDATESERVICEPERMISSIONRESPONSE']._serialized_start=579
  _globals['_UPDATESERVICEPERMISSIONRESPONSE']._serialized_end=612
  _globals['_DELETESERVICEPERMISSIONREQUEST']._serialized_start=614
  _globals['_DELETESERVICEPERMISSIONREQUEST']._serialized_end=658
  _globals['_DELETESERVICEPERMISSIONRESPONSE']._serialized_start=660
  _globals['_DELETESERVICEPERMISSIONRESPONSE']._serialized_end=693
  _globals['_PERMISSIONSERVICE']._serialized_start=696
  _globals['_PERMISSIONSERVICE']._serialized_end=1187
# @@protoc_insertion_point(module_scope)
