# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import permissions_pb2 as permissions__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in permissions_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PermissionServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetPermissionsByService = channel.unary_unary(
                '/permissions.PermissionService/GetPermissionsByService',
                request_serializer=permissions__pb2.GetPermissionsByServiceRequest.SerializeToString,
                response_deserializer=permissions__pb2.GetPermissionsByServiceResponse.FromString,
                _registered_method=True)
        self.CreateServicePermission = channel.unary_unary(
                '/permissions.PermissionService/CreateServicePermission',
                request_serializer=permissions__pb2.CreateServicePermissionRequest.SerializeToString,
                response_deserializer=permissions__pb2.CreateServicePermissionResponse.FromString,
                _registered_method=True)
        self.UpdateServicePermission = channel.unary_unary(
                '/permissions.PermissionService/UpdateServicePermission',
                request_serializer=permissions__pb2.UpdateServicePermissionRequest.SerializeToString,
                response_deserializer=permissions__pb2.UpdateServicePermissionResponse.FromString,
                _registered_method=True)
        self.DeleteServicePermission = channel.unary_unary(
                '/permissions.PermissionService/DeleteServicePermission',
                request_serializer=permissions__pb2.DeleteServicePermissionRequest.SerializeToString,
                response_deserializer=permissions__pb2.DeleteServicePermissionResponse.FromString,
                _registered_method=True)


class PermissionServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetPermissionsByService(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateServicePermission(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateServicePermission(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteServicePermission(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PermissionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetPermissionsByService': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPermissionsByService,
                    request_deserializer=permissions__pb2.GetPermissionsByServiceRequest.FromString,
                    response_serializer=permissions__pb2.GetPermissionsByServiceResponse.SerializeToString,
            ),
            'CreateServicePermission': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateServicePermission,
                    request_deserializer=permissions__pb2.CreateServicePermissionRequest.FromString,
                    response_serializer=permissions__pb2.CreateServicePermissionResponse.SerializeToString,
            ),
            'UpdateServicePermission': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateServicePermission,
                    request_deserializer=permissions__pb2.UpdateServicePermissionRequest.FromString,
                    response_serializer=permissions__pb2.UpdateServicePermissionResponse.SerializeToString,
            ),
            'DeleteServicePermission': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteServicePermission,
                    request_deserializer=permissions__pb2.DeleteServicePermissionRequest.FromString,
                    response_serializer=permissions__pb2.DeleteServicePermissionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'permissions.PermissionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('permissions.PermissionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PermissionService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetPermissionsByService(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/permissions.PermissionService/GetPermissionsByService',
            permissions__pb2.GetPermissionsByServiceRequest.SerializeToString,
            permissions__pb2.GetPermissionsByServiceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateServicePermission(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/permissions.PermissionService/CreateServicePermission',
            permissions__pb2.CreateServicePermissionRequest.SerializeToString,
            permissions__pb2.CreateServicePermissionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateServicePermission(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/permissions.PermissionService/UpdateServicePermission',
            permissions__pb2.UpdateServicePermissionRequest.SerializeToString,
            permissions__pb2.UpdateServicePermissionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteServicePermission(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/permissions.PermissionService/DeleteServicePermission',
            permissions__pb2.DeleteServicePermissionRequest.SerializeToString,
            permissions__pb2.DeleteServicePermissionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
