"""add token.exp column

Revision ID: 11c8f6b3c9e1
Revises: b5a72eb38296
Create Date: 2025-03-12 21:55:08.653923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11c8f6b3c9e1'
down_revision: Union[str, None] = 'b5a72eb38296'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('token', sa.Column('exp', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('token', 'exp')
    # ### end Alembic commands ###
