"""add exteranl_id to role model

Revision ID: 11f3631df4bf
Revises: 5f7a9b105bd8
Create Date: 2025-03-11 22:48:15.843342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11f3631df4bf'
down_revision: Union[str, None] = '5f7a9b105bd8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('external_id', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('role', 'external_id')
    # ### end Alembic commands ###
