"""add ondelete to comment

Revision ID: 160dcb39dbd8
Revises: 232e330d6b5b
Create Date: 2025-04-24 04:42:36.287274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '160dcb39dbd8'
down_revision: Union[str, None] = '232e330d6b5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('comment_application_id_fkey', 'comment', type_='foreignkey')
    op.create_foreign_key(None, 'comment', 'application', ['application_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.create_foreign_key('comment_application_id_fkey', 'comment', 'application', ['application_id'], ['id'])
    # ### end Alembic commands ###
