"""alter Discipline

Revision ID: 1b3096bec0f4
Revises: bd6eaddd47f7
Create Date: 2025-05-19 19:29:11.304658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b3096bec0f4'
down_revision: Union[str, None] = 'bd6eaddd47f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('discipline', sa.Column('elective_group', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('discipline', 'elective_group')
    # ### end Alembic commands ###
