"""alter user

Revision ID: 1be3cfa55347
Revises: c8bdcd28a0a6
Create Date: 2025-05-17 20:24:28.499803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1be3cfa55347'
down_revision: Union[str, None] = 'c8bdcd28a0a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('study_status', sa.String(), nullable=True))
    op.add_column('user', sa.Column('degree_level', sa.String(), nullable=True))
    op.add_column('user', sa.Column('study_group', sa.String(), nullable=True))
    op.add_column('user', sa.Column('specialization', sa.String(), nullable=True))
    op.add_column('user', sa.Column('finance', sa.String(), nullable=True))
    op.add_column('user', sa.Column('form', sa.String(), nullable=True))
    op.add_column('user', sa.Column('enter_year', sa.String(), nullable=True))
    op.alter_column('user', 'sex',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user', 'course',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_column('user', 'group')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('group', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('user', 'course',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('user', 'sex',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('user', 'enter_year')
    op.drop_column('user', 'form')
    op.drop_column('user', 'finance')
    op.drop_column('user', 'specialization')
    op.drop_column('user', 'study_group')
    op.drop_column('user', 'degree_level')
    op.drop_column('user', 'study_status')
    # ### end Alembic commands ###
