"""cascades

Revision ID: 1cc3cce52b28
Revises: dad51f075ee2
Create Date: 2025-02-17 00:54:50.235507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1cc3cce52b28'
down_revision: Union[str, None] = 'dad51f075ee2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('change_application_id_fkey', 'change_application', type_='foreignkey')
    op.create_foreign_key(None, 'change_application', 'application', ['id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('program_application_id_fkey', 'program', type_='foreignkey')
    op.create_foreign_key(None, 'program', 'application', ['application_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('reinstatement_application_id_fkey', 'reinstatement_application', type_='foreignkey')
    op.create_foreign_key(None, 'reinstatement_application', 'application', ['id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('transfer_application_id_fkey', 'transfer_application', type_='foreignkey')
    op.create_foreign_key(None, 'transfer_application', 'application', ['id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transfer_application', type_='foreignkey')
    op.create_foreign_key('transfer_application_id_fkey', 'transfer_application', 'application', ['id'], ['id'])
    op.drop_constraint(None, 'reinstatement_application', type_='foreignkey')
    op.create_foreign_key('reinstatement_application_id_fkey', 'reinstatement_application', 'application', ['id'], ['id'])
    op.drop_constraint(None, 'program', type_='foreignkey')
    op.create_foreign_key('program_application_id_fkey', 'program', 'application', ['application_id'], ['id'])
    op.drop_constraint(None, 'change_application', type_='foreignkey')
    op.create_foreign_key('change_application_id_fkey', 'change_application', 'application', ['id'], ['id'])
    # ### end Alembic commands ###
