"""alter Discipline

Revision ID: 2a469ed95150
Revises: 2e0f5e24172c
Create Date: 2025-05-19 19:23:49.149122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a469ed95150'
down_revision: Union[str, None] = '2e0f5e24172c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('discipline', 'coursework')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('discipline', sa.Column('coursework', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
