"""implement models for rups

Revision ID: 2e0f5e24172c
Revises: 1be3cfa55347
Create Date: 2025-05-18 17:42:52.783222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e0f5e24172c'
down_revision: Union[str, None] = '1be3cfa55347'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discipline',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('control', sa.String(), nullable=False),
    sa.Column('coursework', sa.String(), nullable=False),
    sa.Column('elective_group', sa.String(), nullable=False),
    sa.Column('period', sa.Integer(), nullable=False),
    sa.Column('zet', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['program_id'], ['program.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('discipline_variant',
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=False),
    sa.Column('similarity', sa.Float(), nullable=False),
    sa.Column('choosen', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['target_id'], ['discipline.id'], ),
    sa.ForeignKeyConstraint(['variant_id'], ['discipline.id'], ),
    sa.PrimaryKeyConstraint('target_id', 'variant_id')
    )
    op.add_column('program', sa.Column('with_low_course', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('program', 'with_low_course')
    op.drop_table('discipline_variant')
    op.drop_table('discipline')
    # ### end Alembic commands ###
