"""add exteranl id to user

Revision ID: 3d6d0626451a
Revises: 33d36584b558
Create Date: 2025-03-11 15:47:15.871634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d6d0626451a'
down_revision: Union[str, None] = '33d36584b558'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('external_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'user', ['external_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'external_id')
    # ### end Alembic commands ###
