"""remove column

Revision ID: 407a024156b6
Revises: 160dcb39dbd8
Create Date: 2025-05-02 12:30:06.296140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '407a024156b6'
down_revision: Union[str, None] = '160dcb39dbd8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'filehash')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('filehash', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
