"""add passport fields to user

Revision ID: 4b31aead6670
Revises: b1552e8a8986
Create Date: 2025-03-22 20:39:27.476113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b31aead6670'
down_revision: Union[str, None] = 'b1552e8a8986'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('sex', sa.String(), nullable=False))
    op.add_column('user', sa.Column('birtdate', sa.DateTime(), nullable=False))
    op.add_column('user', sa.Column('passport_series', sa.String(), nullable=False))
    op.add_column('user', sa.Column('passport_birthplace', sa.String(), nullable=False))
    op.add_column('user', sa.Column('passport_issued_by', sa.String(), nullable=False))
    op.add_column('user', sa.Column('passport_issued_code', sa.String(), nullable=False))
    op.add_column('user', sa.Column('passport_issued_date', sa.DateTime(), nullable=False))
    op.drop_column('user', 'passport_data')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('passport_data', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('user', 'passport_issued_date')
    op.drop_column('user', 'passport_issued_code')
    op.drop_column('user', 'passport_issued_by')
    op.drop_column('user', 'passport_birthplace')
    op.drop_column('user', 'passport_series')
    op.drop_column('user', 'birtdate')
    op.drop_column('user', 'sex')
    # ### end Alembic commands ###
