"""add application.user_id

Revision ID: 83feb3e0fa3f
Revises: d0af48e97c76
Create Date: 2025-03-29 18:15:01.568741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83feb3e0fa3f'
down_revision: Union[str, None] = 'd0af48e97c76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application', sa.Column('user_id', sa.String(), nullable=False))
    op.create_foreign_key(None, 'application', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'application', type_='foreignkey')
    op.drop_column('application', 'user_id')
    # ### end Alembic commands ###
