"""alter Discipline

Revision ID: a068ebcb393b
Revises: ed610b7d709b
Create Date: 2025-05-19 19:24:55.205380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a068ebcb393b'
down_revision: Union[str, None] = 'ed610b7d709b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('discipline', 'elective_group',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('discipline', 'elective_group',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
