"""add user type field

Revision ID: b1b9501614ec
Revises: b52b5d6a683d
Create Date: 2025-05-22 20:12:34.189320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1b9501614ec'
down_revision: Union[str, None] = 'b52b5d6a683d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'type')
    # ### end Alembic commands ###
