"""add ondelete

Revision ID: b52b5d6a683d
Revises: 1b3096bec0f4
Create Date: 2025-05-19 19:38:59.721171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b52b5d6a683d'
down_revision: Union[str, None] = '1b3096bec0f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('discipline_program_id_fkey', 'discipline', type_='foreignkey')
    op.create_foreign_key(None, 'discipline', 'program', ['program_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('discipline_variant_target_id_fkey', 'discipline_variant', type_='foreignkey')
    op.drop_constraint('discipline_variant_variant_id_fkey', 'discipline_variant', type_='foreignkey')
    op.create_foreign_key(None, 'discipline_variant', 'discipline', ['variant_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'discipline_variant', 'discipline', ['target_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'discipline_variant', type_='foreignkey')
    op.drop_constraint(None, 'discipline_variant', type_='foreignkey')
    op.create_foreign_key('discipline_variant_variant_id_fkey', 'discipline_variant', 'discipline', ['variant_id'], ['id'])
    op.create_foreign_key('discipline_variant_target_id_fkey', 'discipline_variant', 'discipline', ['target_id'], ['id'])
    op.drop_constraint(None, 'discipline', type_='foreignkey')
    op.create_foreign_key('discipline_program_id_fkey', 'discipline', 'program', ['program_id'], ['id'])
    # ### end Alembic commands ###
