"""alter user passport number field

Revision ID: b5e439c1339c
Revises: 4545e7d525ed
Create Date: 2025-05-22 21:24:44.908262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5e439c1339c'
down_revision: Union[str, None] = '4545e7d525ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'passport_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'passport_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
