"""alter Discipline

Revision ID: bd6eaddd47f7
Revises: a068ebcb393b
Create Date: 2025-05-19 19:29:01.298088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd6eaddd47f7'
down_revision: Union[str, None] = 'a068ebcb393b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('discipline', 'elective_group')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('discipline', sa.Column('elective_group', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
