"""add user passport number field

Revision ID: bdeb4c8b0e05
Revises: d80709b76830
Create Date: 2025-05-22 21:22:19.067010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdeb4c8b0e05'
down_revision: Union[str, None] = 'd80709b76830'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('passport_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'passport_number')
    # ### end Alembic commands ###
