"""initial

Revision ID: c41c7429321b
Revises: 
Create Date: 2025-02-16 21:01:43.732935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c41c7429321b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('surname', sa.String(), nullable=False),
    sa.Column('patronymic', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('snils', sa.String(), nullable=True),
    sa.Column('group', sa.String(), nullable=True),
    sa.Column('course', sa.Integer(), nullable=True),
    sa.Column('passport_data', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('application',
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('hostel_policy_accepted', sa.Boolean(), nullable=False),
    sa.Column('vacation_policy_viewed', sa.Boolean(), nullable=False),
    sa.Column('no_restrictions_policy_accepted', sa.Boolean(), nullable=False),
    sa.Column('reliable_information_policy_accepted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('change_application',
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('change_date', sa.DateTime(), nullable=False),
    sa.Column('purpose', sa.String(length=1023), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['application.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documents',
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('filepath', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['application.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('program',
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('okso', sa.String(), nullable=False),
    sa.Column('profile', sa.String(), nullable=False),
    sa.Column('form', sa.String(), nullable=True),
    sa.Column('base', sa.String(), nullable=True),
    sa.Column('sem_num', sa.Integer(), nullable=True),
    sa.Column('university', sa.String(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['application.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reinstatement_application',
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('is_vacation_need', sa.Boolean(), nullable=False),
    sa.Column('begin_year', sa.Integer(), nullable=False),
    sa.Column('end_year', sa.Integer(), nullable=False),
    sa.Column('purpose', sa.String(), nullable=False),
    sa.Column('paid_policy_accepted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['application.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transfer_application',
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('continue_year', sa.Integer(), nullable=True),
    sa.Column('paid_policy_accepted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['application.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transfer_application')
    op.drop_table('reinstatement_application')
    op.drop_table('program')
    op.drop_table('documents')
    op.drop_table('change_application')
    op.drop_table('application')
    op.drop_table('user')
    # ### end Alembic commands ###
