"""alter user

Revision ID: c8bdcd28a0a6
Revises: df91eb5bdf1a
Create Date: 2025-05-06 20:26:08.656659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8bdcd28a0a6'
down_revision: Union[str, None] = 'df91eb5bdf1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'send_email',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'send_email',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
