"""alter user

Revision ID: df91eb5bdf1a
Revises: 407a024156b6
Create Date: 2025-05-06 20:25:34.528526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df91eb5bdf1a'
down_revision: Union[str, None] = '407a024156b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('send_email', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'send_email')
    # ### end Alembic commands ###
