"""alter Discipline

Revision ID: ed610b7d709b
Revises: 2a469ed95150
Create Date: 2025-05-19 19:24:03.112197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed610b7d709b'
down_revision: Union[str, None] = '2a469ed95150'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('discipline', sa.Column('coursework', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('discipline', 'coursework')
    # ### end Alembic commands ###
