name: Deploy Prod
on:
  push:
    branches:
      - main

jobs:
  deploy-dev:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: network=host

      - name: Build and Push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: localhost:5050/vacancy-back:main
          cache-from: type=registry,ref=localhost:5050/vacancy-back:cache
          cache-to: type=registry,ref=localhost:5050/vacancy-back:cache,mode=max

      - name: Restart Docker Compose
        working-directory: /home/kdadmin/apps/vacancy
        run: |
          docker compose pull vacancy-backend
          docker compose up -d vacancy-backend
